### ISSUE TITLE
Use the Fabric Transfer API

### ISSUE THREAD

**Issue by Technici4n** [Flytre/Pipe#2]
You should look into using the Fabric Transfer API instead of `Inventory`, otherwise insertion into AE2 and MI inventories (and probably countless others) is not going to work. I believe it would be easier to use anyway. If you have any inquiry regarding how to use the API, please let me know and I'll be happy to answer.

**Comment by Flytre** [comment]
The whole point of this project was to try and make pipes independently without a library (as a challenge of skill), so using the Transfer API would undercut that.

**Comment by Technici4n** [comment]
The real challenge would be to make pipes that can actually be used with other mods... :P
If you want your mod to be used more, I'd strongly recommend supporting the standard fabric API. Otherwise, any other pipe mod that is made with support for the standard API is likely to be chosen instead.
